using Oculus.Interaction;
using System.Collections.Generic;
using System.Linq;
using TMPro;
using UnityEngine;

public class PocketSetupManager : MonoBehaviour
{
    [Header("Marker Placement Settings")]
    [Tooltip("Prefab for the pocket marker (must have collider, rigidbody, Grabbable, HandGrabInteractable, etc.).")]
    public GameObject markerPrefab;
    public GameObject pocketMarkerRoot;

    //OVR Controls
    [Tooltip("Reference to left hand OVRHand component (for gesture detection).")]
    public OVRHand leftHand;
    [Tooltip("Reference to right hand OVRHand component (for gesture detection).")]
    public OVRHand rightHand;
    [Tooltip("Event sources for left and right source.")]
    public OVRMicrogestureEventSource LeftHandEventSource;
    public OVRMicrogestureEventSource RightHandEventSource;

    [Tooltip("Reference to the hand visual components.")]
    public HandVisual leftHandVisual;
    public HandVisual rightHandVisual;

    [Header("UI")]
    [Tooltip("Floating instruction text displayed to the user")]
    public TextMeshProUGUI instructionTextUI;

    [Header("Privates")]
    [Tooltip("Floating instruction text displayed to the user")]
    [SerializeField]
    private string _instructionText = string.Empty;
    [SerializeField]
    private sbyte _totalPockedNeeded = 2;

    private float _yCoordinateValueForMarkers = 0;

    private readonly string[] _pocketNames =
    {
        // Manually placed - https://gamedev.stackexchange.com/questions/214545/how-to-virtualize-an-8-ball-pool-table-for-an-ar-game-which-uses-both-real-and-v/214547?noredirect=1#comment390192_214547
        PocketName.TopRightCorner.ToString(),   // (1,2)
        PocketName.BottomLeftCorner.ToString(), // (-1,-2)

        // Autogenerated
        PocketName.MiddleLeftCorner.ToString(), // (-1,0)
        PocketName.BottomRightCorner.ToString(),// (1,-2)
        PocketName.TopLeftCorner.ToString(),    // (-1,2)
        PocketName.MiddleRightCorner.ToString(),// (1,0)
    };

    private Dictionary<byte, Vector3> _pocketWorldPositions = new()
    {
        {(byte) PocketName.TopRightCorner, Vector3.zero },
        {(byte)PocketName.BottomLeftCorner, Vector3.zero},

        {(byte) PocketName.MiddleLeftCorner, Vector3.zero},
        {(byte) PocketName.BottomRightCorner, Vector3.zero },
        {(byte) PocketName.TopLeftCorner, Vector3.zero },
        {(byte) PocketName.MiddleRightCorner, Vector3.zero },
    };

    private List<GameObject> _placedMarkers = null;
    private byte _markersPlacedCount = 0;
    private bool _groupModeActivate = false;
    private bool _allPocketsCalculated = false;

    // Start is called once before the first execution of Update after the MonoBehaviour is created

    private void Awake()
    {

    }
    void Start()
    {
        if (LeftHandEventSource == null || RightHandEventSource == null)
        {
            Debug.LogError($"No {nameof(OVRMicrogestureEventSource)} component attached to this gameobject.");
            return;
        }

        LeftHandEventSource.GestureRecognizedEvent.AddListener(gesture => OnMicrogestureRecognized(leftHand, gesture));
        RightHandEventSource.GestureRecognizedEvent.AddListener(gesture => OnMicrogestureRecognized(rightHand, gesture));

        OVRManager.display.RecenteredPose += HandleRecenter;

        //Initialitze the list of placed markers with 6 empty GameObjects and assign them null value.
        _placedMarkers = new List<GameObject>(_pocketNames.Length);
        for (var i = 0; i < _pocketNames.Length; i++)
        {
            _placedMarkers.Add(null);

        }

        UpdateInstruction("Place the first pocket marker (Top right) by tapping your right thumb on the palm of your right hand. " +
            "You can place up to 2 markers, which will be used to calculate the positions of the other 4 markers. " +
            "Swipe right to finalize placements.");
    }

    // Update is called once per frame
    void Update()
    {
        if (_groupModeActivate) return;

    }

    void OnApplicationQuit()
    {
        LeftHandEventSource.GestureRecognizedEvent.RemoveAllListeners();
        RightHandEventSource.GestureRecognizedEvent.RemoveAllListeners();
    }

    private void OnDestroy()
    {
        LeftHandEventSource.GestureRecognizedEvent.RemoveAllListeners();
        RightHandEventSource.GestureRecognizedEvent.RemoveAllListeners();
        OVRManager.display.RecenteredPose -= HandleRecenter;
    }

    private void OnDisable()
    {
        OVRManager.display.RecenteredPose -= HandleRecenter;
    }

    public void HandleRecenter()
    {
        if (_pocketWorldPositions.All(position => position.Value == Vector3.zero))
        {
            Debug.LogWarning("No pocket markers have been placed yet. Recenter operation will not change anything.");
            return;
        }

        if (_placedMarkers.All(marker => marker == null))
        {
            Debug.LogWarning("No markers have been placed yet. Recenter operation will not change anything.");
            return;
        }

        foreach (var kvp in _pocketWorldPositions)
        {
            if (_placedMarkers[kvp.Key] == null) continue;

            _placedMarkers[kvp.Key].transform.position = kvp.Value;
        }
    }

    public void OnMicrogestureRecognized(OVRHand hand, OVRHand.MicrogestureType gestureType)
    {
        Debug.Log($"Microgesture event: {gestureType} from hand {hand.name}.");

        //Right hand -> HandType is marked as internal.
        var isRightHand = hand.name.ToLower().Contains("right");

        if (isRightHand)
        {
            switch (gestureType)
            {
                case OVRHand.MicrogestureType.ThumbTap:
                    PlaceInitialPocketMarker(hand);
                    break;
                case OVRHand.MicrogestureType.SwipeRight:
                    FinalizePlacements();
                    break;
                case OVRHand.MicrogestureType.SwipeLeft:
                case OVRHand.MicrogestureType.SwipeForward:
                case OVRHand.MicrogestureType.SwipeBackward:
                default:
                    Debug.Log("Gesture currently not supported.");
                    break;
            }
        }

        UpdateInstructionUI();
    }

    private void PlaceInitialPocketMarker(OVRHand hand)
    {
        if (_markersPlacedCount == _totalPockedNeeded)
        {
            UpdateInstruction("All of the required pockets have been instantiated. You can grab them and reposition them, before swiping right.");
            return;
        }

        //if (_groupModeActivate) return;
        if (pocketMarkerRoot == null)
        {
            Debug.LogError("No pocket marker root has been instantiated or has been deleted in runtime, so no (furher) pockets can be placed.");
            return;
        }

        var palmPosition = GetPalmWorldPosition(hand);

        // For the first pocket, store the Y-level
        if (_markersPlacedCount == 0)
        {
            _yCoordinateValueForMarkers = palmPosition.y;
            Debug.Log($"PalmPosition {palmPosition.y}");
            Debug.DrawRay(palmPosition, Vector3.up * 0.1f, Color.green, 2f);
        }

        // Override Y to always match the first pocket’s Y
        palmPosition.y = _yCoordinateValueForMarkers;

        // Instantiate marker at (X,Z) of your hand + fixed Y
        GameObject marker = Instantiate(markerPrefab, palmPosition, Quaternion.identity);
        if (marker.TryGetComponent<XZOnlyConstraint>(out var xzConstraintComponent))
        {
            xzConstraintComponent.Initialize();
        }

        var pocketName = _pocketNames[_markersPlacedCount];
        marker.name = pocketName;
        marker.transform.SetParent(pocketMarkerRoot.transform, worldPositionStays: true);
        marker.transform.localRotation = Quaternion.identity;

        byte enumValueFromPocketName = (byte)(PocketName)System.Enum.Parse(typeof(PocketName), pocketName);

        AddVector3ToVector3FloatDictionary(enumValueFromPocketName, palmPosition);

        _placedMarkers[enumValueFromPocketName] = marker;
        _markersPlacedCount++;

        // Feedback message
        sbyte remaining = (sbyte)(_totalPockedNeeded - _markersPlacedCount);
        _instructionText = remaining > 0
            ? $"<b>{marker.name}</b> placed! {remaining} more to go…"
            : $"<b>{marker.name}</b> placed! Swipe right to confirm.";

        UpdateInstructionUI();
    }

    private void FinalizePlacements()
    {
        if (_allPocketsCalculated)
        {
            _instructionText = "All pockets have been placed at their respected positions. Nothing to do here.";
            Debug.Log(_instructionText);
            UpdateInstruction(_instructionText);
            return;
        }

        if (_markersPlacedCount < _totalPockedNeeded)
        {
            Debug.Log("Cannot finalize: not all required pocket markers are placed yet.");
            return;
        }

        var topRight = (byte)PocketName.TopRightCorner;
        var bottomLeft = (byte)PocketName.BottomLeftCorner;

        Vector3 topRightCorner = _placedMarkers[topRight].transform.position;
        Vector3 bottomLeftCorner = _placedMarkers[bottomLeft].transform.position;

        float midX = (topRightCorner.x + bottomLeftCorner.x) / 2f;
        float midZ = (topRightCorner.z + bottomLeftCorner.z) / 2f;
        float fixedY = topRightCorner.y;

        Vector3 topLeftCorner = new(bottomLeftCorner.x, fixedY, topRightCorner.z);
        Vector3 bottomRightCorner = new(topRightCorner.x, fixedY, bottomLeftCorner.z);

        //Middle corners
        Vector3 middleLeftCorner = new(midX, fixedY, bottomLeftCorner.z);
        Vector3 middleRightCorner = new(midX, fixedY, topLeftCorner.z);

        Vector3[] positions =
        {
            topLeftCorner,
            bottomRightCorner,
            middleLeftCorner,
            middleRightCorner
        };

        byte[] pocketEnums =
        {
            (byte)PocketName.TopLeftCorner,
            (byte)PocketName.BottomRightCorner,
            (byte)PocketName.MiddleLeftCorner,
            (byte)PocketName.MiddleRightCorner
        };

        for (byte i = 0; i < positions.Length; i++)
        {
            GameObject marker = Instantiate(markerPrefab, positions[i], Quaternion.identity);

            if (marker.TryGetComponent<XZOnlyConstraint>(out var xzConstraintComponent))
            {
                xzConstraintComponent.Initialize();
                xzConstraintComponent.GrabbableEnabled = false;
            }

            marker.name = _pocketNames[pocketEnums[i]];
            marker.transform.SetParent(pocketMarkerRoot.transform, worldPositionStays: true);
            marker.transform.localRotation = Quaternion.identity;

            if (_placedMarkers.Count <= pocketEnums[i])
            {
                _placedMarkers.Add(marker);
            }
            else
            {
                _placedMarkers[pocketEnums[i]] = marker;
            }

            AddVector3ToVector3FloatDictionary(pocketEnums[i], positions[i]);
        }

        _markersPlacedCount = 6;

        _instructionText = "All 6 pockets positioned!";
        Debug.Log("All pockets placed and finalized.");
        _allPocketsCalculated = true;
        UpdateInstructionUI();
    }

    private Vector3 GetPalmWorldPosition(OVRHand hand)
    {
        HandVisual handVisual = (hand == leftHand) ? leftHandVisual : rightHandVisual;

        if (handVisual == null)
        {
            Debug.LogWarning("Hand visual component not assigned.");
            return hand.transform.position;
        }

        return handVisual.GetTransformByHandJointId(Oculus.Interaction.Input.HandJointId.HandPalm).position;
    }

    private void UpdateInstruction(string instructionText = "")
    {
        if (!string.IsNullOrEmpty(instructionText))
        {
            _instructionText = instructionText;
            UpdateInstructionUI();
        }
    }

    private void UpdateInstructionUI()
    {
        if (instructionTextUI != null)
        {
            instructionTextUI.text = _instructionText;
            _instructionText = string.Empty;
        }
        else
        {
            Debug.LogWarning("Instruction text UI not assigned.");
        }
    }

    //Extension methods for convenience
    private void AddVector3ToVector3FloatDictionary(byte pocketMarkerNumber, Vector3 value)
    {
        if (!_pocketWorldPositions.ContainsKey(pocketMarkerNumber))
        {
            if (_pocketWorldPositions.Count >= 6)
            {
                Debug.LogError("Cannot add more than 6 pocket markers.");
                return;
            }
            _pocketWorldPositions.Add(pocketMarkerNumber, value);
            Debug.LogError($"Pocket marker number {pocketMarkerNumber} does not exist in the dictionary. It is now added");
        }
        else
        {
            _pocketWorldPositions[pocketMarkerNumber] = value;
            Debug.Log($"Pocket marker number {pocketMarkerNumber} updated with new position: {value}");
        }
    }

    private Vector3 GetVector3FromVector3FloatDictionary(byte pocketMarkerNumber)
    {
        if (_pocketWorldPositions.TryGetValue(pocketMarkerNumber, out Vector3 value))
        {
            Debug.Log($"Pocket marker number {pocketMarkerNumber} has position: {value}");
            return value;
        }
        else
        {
            Debug.LogError($"Pocket marker number {pocketMarkerNumber} does not exist in the dictionary.");
            return Vector3.zero;
        }
    }

    private Dictionary<byte, Vector3Float> GetPocketWorldPositionsToSerializable(Dictionary<byte, Vector3> pocketWorldPositions)
    {
        var pocketWorldPositionsSerializable = new Dictionary<byte, Vector3Float>();
        foreach (var kvp in pocketWorldPositions)
        {
            pocketWorldPositionsSerializable[kvp.Key] = new Vector3Float(kvp.Value);
        }
        return pocketWorldPositionsSerializable;
    }

    private Dictionary<byte, Vector3> GetPocketWorldPositionsFromSerializable(Dictionary<byte, Vector3Float> pocketWorldPositionsSerializable)
    {
        var pocketWorldPositions = new Dictionary<byte, Vector3>();
        foreach (var kvp in pocketWorldPositionsSerializable)
        {
            pocketWorldPositions[kvp.Key] = kvp.Value.FromVector3FloatToVector3();
        }
        return pocketWorldPositions;
    }
}
